# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Production Seed #
SubmissionPeriod.create(active: true)
# End of Production Seed #

Announcement.create(title: 'Start of Submission Period', text: 'We are accepting proposal submissions as of today!', isDraft: false)
Announcement.create(title: 'Scheduled maintenance: 05/13/1996', text: 'We will be performing a scheduled maintenance on the specified date', isDraft: false)
Announcement.create(title: 'Deadline for final report submissions', text: 'Reminder for the requirement of final report', isDraft: false)
Announcement.create(title: 'End of Submission Period', text: 'Proposal submission will be closed', isDraft:false)
Announcement.create(title: 'Results', text: 'Results will be released next week friday', isDraft:false)

Researcher.create(first_name: 'Com', last_name: 'Pyutierre', department: 'MMM', rank: 'Assistant Instructor', contact_number: '9123456789', email: 'mail1@example.com', password: "password", password_confirmation: "password") 
Researcher.create(first_name: 'Palma', last_name: 'Haul', department: 'CoE', rank: 'Professor', contact_number: '9333867460', email: 'mail2@example.com', password: "password", password_confirmation: "password")
Admin.create(first_name: 'Mang', last_name: 'Melchor', department: 'CE', rank: 'Instructor', contact_number: '9835583620', email: 'mail3@example.com', password: "password", password_confirmation: "password")
CommitteeHead.create(first_name: 'Romulo', last_name: 'Hall', department: 'ECE', rank: 'Instructor', contact_number: '9653778294', email: 'mail4@example.com', password: "password", password_confirmation: "password")
CommitteeMember.create(first_name: 'Alfred', last_name: 'Vargas', department: 'CS', rank: '5', contact_number: '9768465839', email: 'mail5@example.com', password: "password", password_confirmation: "password")
Dean.create(first_name: 'Alfred', last_name: 'Vargas', department: 'CS', rank: '5', contact_number: '9768465839', email: 'dean@example.com', password: "password", password_confirmation: "password")

User.first.proposals.create(title: 'Fire Resistant Paper', principal_researcher: 'Com Pyutierre', coresearchers: 'Thomas Edison', rdCost: '123', objectives: 'Make a fire resistant paper', expectedOutputs: 'Fire Resistant Paper', description: 'none', weeklyHours: '5', endorsement: false, submitAgency: true, listAgency: false, attachment: File.open(Rails.root + "app/assets/test_uploads/test.pdf"), recommendation: File.open(Rails.root + "app/assets/test_uploads/test.pdf"), status: 2, is_draft: true)
User.first.proposals.create(title: 'World Peace', principal_researcher: 'Com Pyutierre', coresearchers: 'Mahatma Gandhi', rdCost: '123', objectives: 'Attain inner peace', expectedOutputs: 'World Peace', description: 'none', weeklyHours: '6', endorsement: false, submitAgency: true, listAgency: false, attachment: File.open(Rails.root + "app/assets/test_uploads/test.pdf"), recommendation: File.open(Rails.root + "app/assets/test_uploads/test.pdf"), status: 2, is_draft: false)

User.second.proposals.create(title: 'Fire Resistant Paper', principal_researcher: 'Com Pyutierre', coresearchers: 'Thomas Edison', rdCost: '123', objectives: 'Make a fire resistant paper', expectedOutputs: 'Fire Resistant Paper', description: 'none', weeklyHours: '5', endorsement: false, submitAgency: true, listAgency: false, attachment: File.open(Rails.root + "app/assets/test_uploads/test.pdf"), recommendation: File.open(Rails.root + "app/assets/test_uploads/test.pdf"), status: 2, is_draft: false)
User.second.proposals.create(title: 'World Peace', principal_researcher: 'Com Pyutierre', coresearchers: 'Mahatma Gandhi', rdCost: '123', objectives: 'Attain inner peace', expectedOutputs: 'World Peace', description: 'none', weeklyHours: '6', endorsement: false, submitAgency: true, listAgency: false, attachment: File.open(Rails.root + "app/assets/test_uploads/test.pdf"), recommendation: File.open(Rails.root + "app/assets/test_uploads/test.pdf"), status: 2, is_draft: false)

User.first.proposals.create(title: 'Portable Death Ray', principal_researcher: 'Com Pyutierre', coresearchers: 'Nikola Tesla', rdCost: '123', objectives: 'Make killing a breeze', expectedOutputs: 'Handheld killing device', description: 'none', weeklyHours: '', endorsement: false, submitAgency: true, listAgency: false, attachment: File.open(Rails.root + "app/assets/test_uploads/test.pdf"), recommendation: File.open(Rails.root + "app/assets/test_uploads/test.pdf"), status: 2, is_draft: false)
User.first.proposals.create(title: 'Quantum Computing', principal_researcher: 'Palma Haul', coresearchers: 'Albert Einstein', rdCost: '123', objectives: 'I really dont know', expectedOutputs: 'May magbabasa kaya nito?', description: 'none', weeklyHours: '9', endorsement: false, submitAgency: true, listAgency: false, attachment: File.open(Rails.root + "app/assets/test_uploads/test.pdf"), recommendation: File.open(Rails.root + "app/assets/test_uploads/test.pdf"), status: 2, is_draft: false)
User.first.proposals.create(title: 'Blackholes', principal_researcher: 'Palma Haul', coresearchers: 'Stephen Hawking', rdCost: '123', objectives: 'Understanding that hole', expectedOutputs: 'Blackhole?', description: 'none', weeklyHours: '7', endorsement: false, submitAgency: true, listAgency: false, attachment: File.open(Rails.root + "app/assets/test_uploads/test.pdf"), recommendation: File.open(Rails.root + "app/assets/test_uploads/test.pdf"), status: 2, is_draft: false)
User.first.proposals.create(title: 'Teleportation Ports', principal_researcher: 'Palma Haul', coresearchers: 'Neil Degrasse Tyson', rdCost: '123', objectives: 'Faster travel', expectedOutputs: 'Teleportation Device', description: 'none', weeklyHours: '3', endorsement: false, submitAgency: true, listAgency: false, attachment: File.open(Rails.root + "app/assets/test_uploads/test.pdf"), recommendation: File.open(Rails.root + "app/assets/test_uploads/test.pdf"), status: 2, is_draft: false)

User.second.proposals.create(title: 'Portable Death Ray', principal_researcher: 'Com Pyutierre', coresearchers: 'Nikola Tesla', rdCost: '123', objectives: 'Make killing a breeze', expectedOutputs: 'Handheld killing device', description: 'none', weeklyHours: '', endorsement: false, submitAgency: true, listAgency: false, attachment: File.open(Rails.root + "app/assets/test_uploads/test.pdf"), recommendation: File.open(Rails.root + "app/assets/test_uploads/test.pdf"), status: 2, is_draft: false)
User.second.proposals.create(title: 'Quantum Computing', principal_researcher: 'Palma Haul', coresearchers: 'Albert Einstein', rdCost: '123', objectives: 'I really dont know', expectedOutputs: 'May magbabasa kaya nito?', description: 'none', weeklyHours: '9', endorsement: false, submitAgency: true, listAgency: false, attachment: File.open(Rails.root + "app/assets/test_uploads/test.pdf"), recommendation: File.open(Rails.root + "app/assets/test_uploads/test.pdf"), status: 2, is_draft: false)
User.second.proposals.create(title: 'Blackholes', principal_researcher: 'Palma Haul', coresearchers: 'Stephen Hawking', rdCost: '123', objectives: 'Understanding that hole', expectedOutputs: 'Blackhole?', description: 'none', weeklyHours: '7', endorsement: false, submitAgency: true, listAgency: false, attachment: File.open(Rails.root + "app/assets/test_uploads/test.pdf"), recommendation: File.open(Rails.root + "app/assets/test_uploads/test.pdf"), status: 2, is_draft: false)
User.second.proposals.create(title: 'Teleportation Ports', principal_researcher: 'Palma Haul', coresearchers: 'Neil Degrasse Tyson', rdCost: '123', objectives: 'Faster travel', expectedOutputs: 'Teleportation Device', description: 'none', weeklyHours: '3', endorsement: false, submitAgency: true, listAgency: false, attachment: File.open(Rails.root + "app/assets/test_uploads/test.pdf"), recommendation: File.open(Rails.root + "app/assets/test_uploads/test.pdf"), status: 2, is_draft: false)
